services:
  - type: web
    name: spellfinder-pf1e
    runtime: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt && python init_db.py && python categorization/import_categories.py"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
